jobs:
  - job: "Install_Packages_and_Lint"
    pool:
      vmImage: "ubuntu-20.04"

    steps:
      - task: UsePythonVersion@0
        displayName: Use python 3.8.3
        inputs:
          versionSpec: "3.8.3"

      - script: |
          python -m pip install --upgrade pip setuptools wheel pipenv
          python -m pipenv sync --dev

        displayName: "Installing dependencies"

      - script: |
          python -m pipenv run isort -c -df

        displayName: "Check import order"

      - script: |
          python -m pipenv run lint

        displayName: "Check code style with flake8"
