trigger:
  - master

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.3'

  - script: |
      python -m pip install --upgrade pip setuptools wheel pipenv
      python -m pipenv sync --dev

    displayName: "Installing dependencies"

  - script: |
      pipenv run lint

    displayName: "Check code style with flake8"
